# Generated by Django 4.2 on 2023-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cyber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ism")),
                ("email", models.EmailField(max_length=255)),
                (
                    "phone",
                    models.IntegerField(max_length=15, verbose_name="Telefon raqam"),
                ),
            ],
        ),
    ]
