# Generated by Django 4.2 on 2023-04-14 07:15

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0002_alter_cyber_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyber",
            name="discription",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cyber",
            name="photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="start/images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cyber",
            name="short_discription",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cyber",
            name="phone",
            field=models.BigIntegerField(verbose_name="Telefon raqam"),
        ),
    ]
